version: 2.1

orbs:
  python: circleci/python@0.3.0

jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout

      - run: sudo apt-get -y update
      - run: sudo apt-get -y install g++ build-essential make autoconf libglfw3-dev libsdl2-image-dev libsdl2-dev libczmq-dev cppcheck

      - run:
          name: Cppcheck
          command: cppcheck Project

      - run:
          name: Execute Makefile
          working_directory: Project
          command: make -j 4

workflows:
  main:
    jobs:
      - build
